# 2.2数据操作

In [1]:
import torch

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[-9.2059e+08,  3.0634e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.3452e-43],
        [ 0.0000e+00,  0.0000e+00,  9.2196e-41],
        [ 0.0000e+00,  0.0000e+00, -1.5970e-23]])


In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.4790, 0.0421, 0.5513],
        [0.7146, 0.8573, 0.2692],
        [0.1834, 0.1797, 0.6545],
        [0.8410, 0.5031, 0.2531],
        [0.2564, 0.6409, 0.0034]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


$linspace$均匀分，$normal$正太分布，$uniform$均匀分布。

In [10]:
x=torch.rand(5,3)
y=torch.rand(5,3)
z=torch.rand(5,3)
torch.add(x,y,out=z)
y.add_(x)
print(x,y,z)

tensor([[0.8053, 0.8579, 0.6674],
        [0.8913, 0.5655, 0.7309],
        [0.8178, 0.2700, 0.6136],
        [0.7132, 0.7802, 0.5807],
        [0.2781, 0.9951, 0.4703]]) tensor([[1.2363, 1.4053, 1.1709],
        [1.0768, 1.2469, 1.3623],
        [1.0972, 0.4235, 1.4190],
        [1.2353, 1.4899, 1.0743],
        [0.5098, 1.1044, 1.1792]]) tensor([[1.2363, 1.4053, 1.1709],
        [1.0768, 1.2469, 1.3623],
        [1.0972, 0.4235, 1.4190],
        [1.2353, 1.4899, 1.0743],
        [0.5098, 1.1044, 1.1792]])


索引数据与原数据共享内存,高级索引函数查文档即可

In [11]:
k=z[0,:]
print(z[0,:])
k+=1
print(z[0,:])

tensor([1.2363, 1.4053, 1.1709])
tensor([2.2363, 2.4053, 2.1709])


$view$可以改变$tensor$的形状，一个维度可以设置为$-1$，大小根据其他$n-1$维推出，$view$改变后得到的新变量与原变量共享内存

In [12]:
xx=x.view(15)
yy=y.view(-1,5)
print(x,xx,y,yy)
yy+=1
print(x,xx,y,yy)

tensor([[0.8053, 0.8579, 0.6674],
        [0.8913, 0.5655, 0.7309],
        [0.8178, 0.2700, 0.6136],
        [0.7132, 0.7802, 0.5807],
        [0.2781, 0.9951, 0.4703]]) tensor([0.8053, 0.8579, 0.6674, 0.8913, 0.5655, 0.7309, 0.8178, 0.2700, 0.6136,
        0.7132, 0.7802, 0.5807, 0.2781, 0.9951, 0.4703]) tensor([[1.2363, 1.4053, 1.1709],
        [1.0768, 1.2469, 1.3623],
        [1.0972, 0.4235, 1.4190],
        [1.2353, 1.4899, 1.0743],
        [0.5098, 1.1044, 1.1792]]) tensor([[1.2363, 1.4053, 1.1709, 1.0768, 1.2469],
        [1.3623, 1.0972, 0.4235, 1.4190, 1.2353],
        [1.4899, 1.0743, 0.5098, 1.1044, 1.1792]])
tensor([[0.8053, 0.8579, 0.6674],
        [0.8913, 0.5655, 0.7309],
        [0.8178, 0.2700, 0.6136],
        [0.7132, 0.7802, 0.5807],
        [0.2781, 0.9951, 0.4703]]) tensor([0.8053, 0.8579, 0.6674, 0.8913, 0.5655, 0.7309, 0.8178, 0.2700, 0.6136,
        0.7132, 0.7802, 0.5807, 0.2781, 0.9951, 0.4703]) tensor([[2.2363, 2.4053, 2.1709],
        [2.0768, 2.2469, 2.3

如果想改变形状后的变量与原变量不共享内存，可以先$clone$后再对$clone$进行$view$。$clone$后再$view$和$reshape$对比还有不同在于会被记录在计算图中。

In [13]:
yyy=y.clone().view(-1,5)
yyy-=1
print(y,yyy)

tensor([[2.2363, 2.4053, 2.1709],
        [2.0768, 2.2469, 2.3623],
        [2.0972, 1.4235, 2.4190],
        [2.2353, 2.4899, 2.0743],
        [1.5098, 2.1044, 2.1792]]) tensor([[1.2363, 1.4053, 1.1709, 1.0768, 1.2469],
        [1.3623, 1.0972, 0.4235, 1.4190, 1.2353],
        [1.4899, 1.0743, 0.5098, 1.1044, 1.1792]])


In [14]:
yyy[0,0].item()

1.2362990379333496

支持的线性代数操作查文档即可
广播机制即不同大小的tensor也可做运算

In [17]:
a=torch.rand(1,3)
b=torch.rand(3,1)
c=torch.rand(3,3)
torch.add(a,b,out=c)
print(a,b,c)

tensor([[0.9767, 0.5459, 0.0932]]) tensor([[0.2042],
        [0.9041],
        [0.1361]]) tensor([[1.1809, 0.7501, 0.2974],
        [1.8808, 1.4500, 0.9972],
        [1.1128, 0.6820, 0.2292]])


$y=x+y$ 与 $y+=x$ $y.add_(x)$ $torch.add(x,y,out=y)$ 的不同在于后面的方法不会开辟新内存而第一个的y指向了新内存

In [18]:
num=c.numpy()
num+=1
print(c,num)

tensor([[2.1809, 1.7501, 1.2974],
        [2.8808, 2.4500, 1.9972],
        [2.1128, 1.6820, 1.2292]]) [[2.180908  1.7501341 1.2973703]
 [2.8807812 2.4500072 1.9972434]
 [2.1127646 1.6819906 1.2292268]]


In [19]:
import numpy as np
a=np.ones(5)
c=torch.from_numpy(a)
c+=1
print(a,c)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
