## 自动求梯度

In [1]:
import torch

In [2]:
x=torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
x.grad_fn

In [4]:
print(x.grad_fn)

None


In [5]:
y=x+2
z=y*y*3
out=z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [6]:
out.backward()

In [7]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [8]:
out2=x.sum()

In [9]:
out2

tensor(4., grad_fn=<SumBackward0>)

In [10]:
out2.backward()

In [11]:
x.grad

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])

In [12]:
out3=x.sum()
x.grad.data.zero_()
out3.backward()
out3.grad

In [13]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

向量的$backward$需要传入一个同型的向量使得运算后成为一个标量然后用标量进行求导。假设$ｙ$由$ｘ$得到，那么$y.backward(w)$的含义是先计算$l=torch.sum(y*w)$ 那么$l$是一个标量，只需要求$l$对$x$的偏导即可。

In [14]:
x=torch.tensor([1.0,1.0,1.0,1.0],requires_grad=True)
y=2*x
z=y.view(2,2)
z

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ViewBackward>)

In [15]:
v=torch.tensor([[1.0,2.0],[3.0,4.0]],dtype=torch.float)
z.backward(v)
x.grad

tensor([2., 4., 6., 8.])

In [16]:
x=torch.ones(2,2)
x.requires_grad_(True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [20]:
y=3*x
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>)

In [25]:
y.backward(v)
x.grad

tensor([[ 3.,  6.],
        [ 9., 12.]])